services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main
    volumes:
      - ./src:/app:ro
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    command: python3.12 -m main

